name: FibCalc

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set semver tag
        uses: docker/metadata-action@v1
        with:
          metadata-path: ./.github/metadata.json
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          registry: ghcr.io
          push: true
          cache-from:
            - type: registry
              registry: docker.io
          platforms: linux/amd64,linux/arm64,darwin/amd64
          buildkit: true
          oci: true
          tags: student/fibcalc:${{ github.ref }}.${{ steps.metadata.outputs.tag }}
